#config ini adalah untuk konfigurasi-konfigurasi chatbot yang akan dipakai, con: nama chatbot, base url api, customize error/timeout message dll
botDisplayName: Stadia #konfigurasi nama chatbot
faqs: #topik untuk faq
  website:
    title: "Apa nestle indonesia punya website?"
    desc: 
          - "Faiz informasikan untuk website pizza indonesia kamu bisa akses di https://www.nestle.co.id/"
          -  "untuk website pizza indonesia kamu bisa akses di https://www.nestle.co.id/"
  pemesanan:
    title: "Apakah saya bisa pesan online?"
    desc: "Untuk pemesanan online bisa melalui chat ini atau menggunakan e-commerce"
  jobvacancy:
    title: "Bagaimana jika ingin bertanya seputar lowongan pekerjaan?"
    desc: "Untuk lowongan pekerjaan di Nestle Indonesia dapat datang langsung ke outlet terdekat atau bisa kirimkan CV melalui email ke career@nestle.co.id"
  promo:
    title: "Apa ada promo?"
    desc:   
          - "Untuk promo bulan ini kami hanya mengeluarkan promo untuk pemesanan offline, silahkan tunggu promo menarik lainnya! :)"
          - "untuk website pizza indonesia kamu bisa akses di https://www.nestle.co.id/"
  payment:
    title: "Apa saja metode pembayaran yang dapat digunakan?"
    desc: "Melalui website, kamu dapat membayar pesanan melalui dua cara yaitu Online Payment dan Payment on Delivery. Online Payment terdiri dari Credit Card, Doku Wallets dan BCA Virtual Account. Sedangkan, Payment on Delivery yaitu pembayaran melalui Delivery Man yang mengantarkan jika kamu memilih layanan Delivery yaitu terdiri dari Swipe on Delivery melalui mesin EDC dan pembayaran secara cash"
